In [1]:
import pandas as pd

In [6]:
file = './data/201812_201812_주민등록인구및세대현황_월간.xlsx'
raw = pd.read_excel(file, header = 2)
raw.head(10)

,행정기관,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율
0,서울특별시 (1100000000),"9,765,623","4,263,868",2.29,"4,773,899","4,991,724",0.96
1,서울특별시 종로구 (1111000000),"153,065","73,735",2.08,"74,825","78,240",0.96
2,서울특별시 중구 (1114000000),"125,725","61,502",2.04,"61,947","63,778",0.97
3,서울특별시 용산구 (1117000000),"228,999","108,974",2.10,"110,640","118,359",0.93
4,서울특별시 성동구 (1120000000),"308,221","137,209",2.25,"151,359","156,862",0.96
5,서울특별시 광진구 (1121500000),"355,559","162,606",2.19,"172,794","182,765",0.95
6,서울특별시 동대문구 (1123000000),"348,052","161,820",2.15,"173,567","174,485",0.99
7,서울특별시 중랑구 (1126000000),"403,209","180,511",2.23,"200,419","202,790",0.99
8,서울특별시 성북구 (1129000000),"435,868","186,601",2.34,"211,904","223,964",0.95
9,서울특별시 강북구 (1130500000),"319,164","143,395",2.23,"156,071","163,093",0.96

In [7]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   행정기관    278 non-null    object
 1   총인구수    278 non-null    object
 2   세대수     278 non-null    object
 3   세대당 인구  278 non-null    float64
 4   남자 인구수  278 non-null    object
 5   여자 인구수  278 non-null    object
 6   남여 비율   278 non-null    float64
dtypes: float64(2), object(5)
memory usage: 15.3+ KB

In [8]:
raw.describe()

           세대당 인구       남여 비율
count  278.000000  278.000000
mean     2.258417    1.004424
std      0.215634    0.050886
min      1.790000    0.900000
25%      2.072500    0.970000
50%      2.260000    1.000000
75%      2.430000    1.030000
max      2.790000    1.310000

In [ ]:
#1. hearder 시작위치 변경 / 완료
#2. 치킨집 데이터와 병합할 수 있도록 지역 값 형태 변경
#3. 총인구수  : 문자  ---> 숫자

In [9]:
raw.head(3)

,행정기관,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율
0,서울특별시 (1100000000),"9,765,623","4,263,868",2.29,"4,773,899","4,991,724",0.96
1,서울특별시 종로구 (1111000000),"153,065","73,735",2.08,"74,825","78,240",0.96
2,서울특별시 중구 (1114000000),"125,725","61,502",2.04,"61,947","63,778",0.97

In [ ]:
# 인구 데이터 서울특별시 종로구 (1111000000) --> "서울특별시 종로구 "
# 치킨 데이터 "서울특별시" "종로구" --> "서울특별시 종로구 "

In [16]:
temp_list = []

for c in raw['행정기관'] :
    #print(c[:-13])
    temp = c.split(' (')[0] # 앞뒤로 나누어서 정리하는 방법
    #temp = c[:-13] 글자수로 정리하는 방법 
    print(temp)
    temp_list.append(temp)
    # 코드 정리 방법
    #### 길이수가 같으면 --> c[:-13]
    #### "()" 기준으로 데이터 split --> temp = c.split(' (')[0]

서울특별시
서울특별시 종로구
서울특별시 중구
서울특별시 용산구
서울특별시 성동구
서울특별시 광진구
서울특별시 동대문구
서울특별시 중랑구
서울특별시 성북구
서울특별시 강북구
서울특별시 도봉구
서울특별시 노원구
서울특별시 은평구
서울특별시 서대문구
서울특별시 마포구
서울특별시 양천구
서울특별시 강서구
서울특별시 구로구
서울특별시 금천구
서울특별시 영등포구
서울특별시 동작구
서울특별시 관악구
서울특별시 서초구
서울특별시 강남구
서울특별시 송파구
서울특별시 강동구
부산광역시
부산광역시 중구
부산광역시 서구
부산광역시 동구
부산광역시 영도구
부산광역시 부산진구
부산광역시 동래구
부산광역시 남구
부산광역시 북구
부산광역시 해운대구
부산광역시 사하구
부산광역시 금정구
부산광역시 강서구
부산광역시 연제구
부산광역시 수영구
부산광역시 사상구
부산광역시 기장군
대구광역시
대구광역시 중구
대구광역시 동구
대구광역시 서구
대구광역시 남구
대구광역시 북구
대구광역시 수성구
대구광역시 달서구
대구광역시 달성군
인천광역시
인천광역시 중구
인천광역시 동구
인천광역시 미추홀구
인천광역시 연수구
인천광역시 남동구
인천광역시 부평구
인천광역시 계양구
인천광역시 서구
인천광역시 강화군
인천광역시 옹진군
광주광역시
광주광역시 동구
광주광역시 서구
광주광역시 남구
광주광역시 북구
광주광역시 광산구
대전광역시
대전광역시 동구
대전광역시 중구
대전광역시 서구
대전광역시 유성구
대전광역시 대덕구
울산광역시
울산광역시 중구
울산광역시 남구
울산광역시 동구
울산광역시 북구
울산광역시 울주군
세종특별자치시
세종특별자치시
경기도
경기도 수원시
경기도 수원시 장안구
경기도 수원시 권선구
경기도 수원시 팔달구
경기도 수원시 영통구
경기도 성남시
경기도 성남시 수정구
경기도 성남시 중원구
경기도 성남시 분당구
경기도 의정부시
경기도 안양시
경기도 안양시 만안구
경기도 안양시 동안구
경기도 부천시
경기도 광명시
경기도 평택시
경기도 동두천시
경기도 안산시
경기도 안산시 상록구
경기도 안산시 단원구
경기도 고양시
경기도 고양시 덕양구
경기도 고양시 일산동구
경기도 고양시 일산서구
경기도 과천시
경기도 구리시
경기도 남양주시
경기도 오산시
경기도 시흥시
경기도 군포시
경기도 의왕시
경기도 하남시
경기도 용인시
경기도 용인시 처인구
경기도 용인시 기흥구
경기도 용인시 수지구
경기도 파주시
경기도 이천시
경기도 안성시
경기도 김포시
경기도 화성시
경기도 광주시
경기도 양주시
경기도 포천시
경기도 여주시
경기도 연천군
경기도 가평군
경기도 양평군
강원도
강원도 춘천시
강원도 원주시
강원도 강릉시
강원도 동해시
강원도 태백시
강원도 속초시
강원도 삼척시
강원도 홍천군
강원도 횡성군
강원도 영월군
강원도 평창군
강원도 정선군
강원도 철원군
강원도 화천군
강원도 양구군
강원도 인제군
강원도 고성군
강원도 양양군
충청북도
충청북도 청주시
충청북도 청주시 상당구
충청북도 청주시 서원구
충청북도 청주시 흥덕구
충청북도 청주시 청원구
충청북도 충주시
충청북도 제천시
충청북도 보은군
충청북도 옥천군
충청북도 영동군
충청북도 증평군
충청북도 진천군
충청북도 괴산군
충청북도 음성군
충청북도 단양군
충청남도
충청남도 천안시
충청남도 천안시 동남구
충청남도 천안시 서북구
충청남도 공주시
충청남도 보령시
충청남도 아산시
충청남도 서산시
충청남도 논산시
충청남도 계룡시
충청남도 당진시
충청남도 금산군
충청남도 부여군
충청남도 서천군
충청남도 청양군
충청남도 홍성군
충청남도 예산군
충청남도 태안군
전라북도
전라북도 전주시
전라북도 전주시 완산구
전라북도 전주시 덕진구
전라북도 군산시
전라북도 익산시
전라북도 정읍시
전라북도 남원시
전라북도 김제시
전라북도 완주군
전라북도 진안군
전라북도 무주군
전라북도 장수군
전라북도 임실군
전라북도 순창군
전라북도 고창군
전라북도 부안군
전라남도
전라남도 목포시
전라남도 여수시
전라남도 순천시
전라남도 나주시
전라남도 광양시
전라남도 담양군
전라남도 곡성군
전라남도 구례군
전라남도 고흥군
전라남도 보성군
전라남도 화순군
전라남도 장흥군
전라남도 강진군
전라남도 해남군
전라남도 영암군
전라남도 무안군
전라남도 함평군
전라남도 영광군
전라남도 장성군
전라남도 완도군
전라남도 진도군
전라남도 신안군
경상북도
경상북도 포항시
경상북도 포항시 남구
경상북도 포항시 북구
경상북도 경주시
경상북도 김천시
경상북도 안동시
경상북도 구미시
경상북도 영주시
경상북도 영천시
경상북도 상주시
경상북도 문경시
경상북도 경산시
경상북도 군위군
경상북도 의성군
경상북도 청송군
경상북도 영양군
경상북도 영덕군
경상북도 청도군
경상북도 고령군
경상북도 성주군
경상북도 칠곡군
경상북도 예천군
경상북도 봉화군
경상북도 울진군
경상북도 울릉군
경상남도
경상남도 창원시
경상남도 창원시 의창구
경상남도 창원시 성산구
경상남도 창원시 마산합포구
경상남도 창원시 마산회원구
경상남도 창원시 진해구
경상남도 진주시
경상남도 통영시
경상남도 사천시
경상남도 김해시
경상남도 밀양시
경상남도 거제시
경상남도 양산시
경상남도 의령군
경상남도 함안군
경상남도 창녕군
경상남도 고성군
경상남도 남해군
경상남도 하동군
경상남도 산청군
경상남도 함양군
경상남도 거창군
경상남도 합천군
제주특별자치도
제주특별자치도 제주시
제주특별자치도 서귀포시

In [17]:
temp_list

['서울특별시 ',
 '서울특별시 종로구',
 '서울특별시 중구',
 '서울특별시 용산구',
 '서울특별시 성동구',
 '서울특별시 광진구',
 '서울특별시 동대문구',
 '서울특별시 중랑구',
 '서울특별시 성북구',
 '서울특별시 강북구',
 '서울특별시 도봉구',
 '서울특별시 노원구',
 '서울특별시 은평구',
 '서울특별시 서대문구',
 '서울특별시 마포구',
 '서울특별시 양천구',
 '서울특별시 강서구',
 '서울특별시 구로구',
 '서울특별시 금천구',
 '서울특별시 영등포구',
 '서울특별시 동작구',
 '서울특별시 관악구',
 '서울특별시 서초구',
 '서울특별시 강남구',
 '서울특별시 송파구',
 '서울특별시 강동구',
 '부산광역시 ',
 '부산광역시 중구',
 '부산광역시 서구',
 '부산광역시 동구',
 '부산광역시 영도구',
 '부산광역시 부산진구',
 '부산광역시 동래구',
 '부산광역시 남구',
 '부산광역시 북구',
 '부산광역시 해운대구',
 '부산광역시 사하구',
 '부산광역시 금정구',
 '부산광역시 강서구',
 '부산광역시 연제구',
 '부산광역시 수영구',
 '부산광역시 사상구',
 '부산광역시 기장군',
 '대구광역시 ',
 '대구광역시 중구',
 '대구광역시 동구',
 '대구광역시 서구',
 '대구광역시 남구',
 '대구광역시 북구',
 '대구광역시 수성구',
 '대구광역시 달서구',
 '대구광역시 달성군',
 '인천광역시 ',
 '인천광역시 중구',
 '인천광역시 동구',
 '인천광역시 미추홀구',
 '인천광역시 연수구',
 '인천광역시 남동구',
 '인천광역시 부평구',
 '인천광역시 계양구',
 '인천광역시 서구',
 '인천광역시 강화군',
 '인천광역시 옹진군',
 '광주광역시 ',
 '광주광역시 동구',
 '광주광역시 서구',
 '광주광역시 남구',
 '광주광역시 북구',
 '광주광역시 광산구',
 '대전광역시 ',
 '대전광역시 동구',
 '대전광역시 중구',
 '대전광역시 서구',
 '대전광역시 유성구',
 '대전광역시 대덕구',
 '울산광역시 ',
 '울산광역시 중구',
 '울산광역시 남구',
 '울산광역시 동구',
 '울산광역시 북구',
 '울산광역시 울주군',
 '세종특별자치시 ',
 '세종특별자치시 ',
 '경기도 ',
 '경기도 수원시',
 '경기도 수원시 장안구',
 '경기도 수원시 권선구',
 '경기도 수원시 팔달구',
 '경기도 수원시 영통구',
 '경기도 성남시',
 '경기도 성남시 수정구',
 '경기도 성남시 중원구',
 '경기도 성남시 분당구',
 '경기도 의정부시',
 '경기도 안양시',
 '경기도 안양시 만안구',
 '경기도 안양시 동안구',
 '경기도 부천시',
 '경기도 광명시',
 '경기도 평택시',
 '경기도 동두천시',
 '경기도 안산시',
 '경기도 안산시 상록구',
 '경기도 안산시 단원구',
 '경기도 고양시',
 '경기도 고양시 덕양구',
 '경기도 고양시 일산동구',
 '경기도 고양시 일산서구',
 '경기도 과천시',
 '경기도 구리시',
 '경기도 남양주시',
 '경기도 오산시',
 '경기도 시흥시',
 '경기도 군포시',
 '경기도 의왕시',
 '경기도 하남시',
 '경기도 용인시',
 '경기도 용인시 처인구',
 '경기도 용인시 기흥구',
 '경기도 용인시 수지구',
 '경기도 파주시',
 '경기도 이천시',
 '경기도 안성시',
 '경기도 김포시',
 '경기도 화성시',
 '경기도 광주시',
 '경기도 양주시',
 '경기도 포천시',
 '경기도 여주시',
 '경기도 연천군',
 '경기도 가평군',
 '경기도 양평군',
 '강원도 ',
 '강원도 춘천시',
 '강원도 원주시',
 '강원도 강릉시',
 '강원도 동해시',
 '강원도 태백시',
 '강원도 속초시',
 '강원도 삼척시',
 '강원도 홍천군',
 '강원도 횡성군',
 '강원도 영월군',
 '강원도 평창군',
 '강원도 정선군',
 '강원도 철원군',
 '강원도 화천군',
 '강원도 양구군',
 '강원도 인제군',
 '강원도 고성군',
 '강원도 양양군',
 '충청북도 ',
 '충청북도 청주시',
 '충청북도 청주시 상당구',
 '충청북도 청주시 서원구',
 '충청북도 청주시 흥덕구',
 '충청북도 청주시 청원구',
 '충청북도 충주시',
 '충청북도 제천시',
 '충청북도 보은군',
 '충청북도 옥천군',
 '충청북도 영동군',
 '충청북도 증평군',
 '충청북도 진천군',
 '충청북도 괴산군',
 '충청북도 음성군',
 '충청북도 단양군',
 '충청남도 ',
 '충청남도 천안시',
 '충청남도 천안시 동남구',
 '충청남도 천안시 서북구',
 '충청남도 공주시',
 '충청남도 보령시',
 '충청남도 아산시',
 '충청남도 서산시',
 '충청남도 논산시',
 '충청남도 계룡시',
 '충청남도 당진시',
 '충청남도 금산군',
 '충청남도 부여군',
 '충청남도 서천군',
 '충청남도 청양군',
 '충청남도 홍성군',
 '충청남도 예산군',
 '충청남도 태안군',
 '전라북도 ',
 '전라북도 전주시',
 '전라북도 전주시 완산구',
 '전라북도 전주시 덕진구',
 '전라북도 군산시',
 '전라북도 익산시',
 '전라북도 정읍시',
 '전라북도 남원시',
 '전라북도 김제시',
 '전라북도 완주군',
 '전라북도 진안군',
 '전라북도 무주군',
 '전라북도 장수군',
 '전라북도 임실군',
 '전라북도 순창군',
 '전라북도 고창군',
 '전라북도 부안군',
 '전라남도 ',
 '전라남도 목포시',
 '전라남도 여수시',
 '전라남도 순천시',
 '전라남도 나주시',
 '전라남도 광양시',
 '전라남도 담양군',
 '전라남도 곡성군',
 '전라남도 구례군',
 '전라남도 고흥군',
 '전라남도 보성군',
 '전라남도 화순군',
 '전라남도 장흥군',
 '전라남도 강진군',
 '전라남도 해남군',
 '전라남도 영암군',
 '전라남도 무안군',
 '전라남도 함평군',
 '전라남도 영광군',
 '전라남도 장성군',
 '전라남도 완도군',
 '전라남도 진도군',
 '전라남도 신안군',
 '경상북도 ',
 '경상북도 포항시',
 '경상북도 포항시 남구',
 '경상북도 포항시 북구',
 '경상북도 경주시',
 '경상북도 김천시',
 '경상북도 안동시',
 '경상북도 구미시',
 '경상북도 영주시',
 '경상북도 영천시',
 '경상북도 상주시',
 '경상북도 문경시',
 '경상북도 경산시',
 '경상북도 군위군',
 '경상북도 의성군',
 '경상북도 청송군',
 '경상북도 영양군',
 '경상북도 영덕군',
 '경상북도 청도군',
 '경상북도 고령군',
 '경상북도 성주군',
 '경상북도 칠곡군',
 '경상북도 예천군',
 '경상북도 봉화군',
 '경상북도 울진군',
 '경상북도 울릉군',
 '경상남도 ',
 '경상남도 창원시',
 '경상남도 창원시 의창구',
 '경상남도 창원시 성산구',
 '경상남도 창원시 마산합포구',
 '경상남도 창원시 마산회원구',
 '경상남도 창원시 진해구',
 '경상남도 진주시',
 '경상남도 통영시',
 '경상남도 사천시',
 '경상남도 김해시',
 '경상남도 밀양시',
 '경상남도 거제시',
 '경상남도 양산시',
 '경상남도 의령군',
 '경상남도 함안군',
 '경상남도 창녕군',
 '경상남도 고성군',
 '경상남도 남해군',
 '경상남도 하동군',
 '경상남도 산청군',
 '경상남도 함양군',
 '경상남도 거창군',
 '경상남도 합천군',
 '제주특별자치도 ',
 '제주특별자치도 제주시',
 '제주특별자치도 서귀포시']

In [18]:
raw['시군구정리'] = temp_list
raw.head()

,행정기관,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율,시군구정리
0,서울특별시 (1100000000),"9,765,623","4,263,868",2.29,"4,773,899","4,991,724",0.96,서울특별시
1,서울특별시 종로구 (1111000000),"153,065","73,735",2.08,"74,825","78,240",0.96,서울특별시 종로구
2,서울특별시 중구 (1114000000),"125,725","61,502",2.04,"61,947","63,778",0.97,서울특별시 중구
3,서울특별시 용산구 (1117000000),"228,999","108,974",2.10,"110,640","118,359",0.93,서울특별시 용산구
4,서울특별시 성동구 (1120000000),"308,221","137,209",2.25,"151,359","156,862",0.96,서울특별시 성동구

In [20]:
raw['시군구정리'].unique()
raw['시군구정리'].value_counts()

세종특별자치시     2
대전광역시       1
경기도 수원시     1
경상북도 영주시    1
인천광역시 중구    1
           ..
강원도         1
경기도 양주시     1
충청남도 부여군    1
경상북도 구미시    1
충청남도 홍성군    1
Name: 시군구정리, Length: 277, dtype: int64

In [21]:
raw.to_excel('./population.xlsx', index = False)